// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteFile(arg1:string):Promise<void>;

export function GetDirectoryContent(arg1:string):Promise<main.entryList>;

export function GetDrives():Promise<Array<string>>;

export function GetHomeDirectory():Promise<main.directory>;

export function Greet(arg1:string):Promise<string>;
