// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteFile(arg1) {
  return window['go']['main']['App']['ExecuteFile'](arg1);
}

export function GetDirectoryContent(arg1) {
  return window['go']['main']['App']['GetDirectoryContent'](arg1);
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
